[[items]]
name = "Neovim"
src = "nvim"
dest = "~/.config/nvim"

[[items]]
name = "Doom Emacs"
src = "doom"
dest = "~/.config/nvim"

[[items]]
name = "Kitty"
src = "kitty"
dest = "~/.config/kitty"

[[items]]
name = "Fish"
src = "fish"
dest = "~/.config/fish"

[[items]]
name = "Fastfetch"
src = "fastfetch"
dest = "~/.config/fastfetch"
